### ISSUE TITLE
Support Translatable

### ISSUE THREAD

**Issue by wajdijurry** [Lupennat/nova-nested-many#10]
I am using this package, and it is very helpful, but I am facing an issue with a translatable nested field:

Product resource:
```
class Product extends Resource {
    public function fields()
    {
        return [
            HasManyNested::make('Variations', 'variations', Variation::class)
                ->hideWhenCreating()
                ->propagate('id')
                ->hideFromIndex()
                ->useTabs(),
        ];
    }
}
```

Variation resource:
```
class Variation extends Resource {
    public function fields()
    {
        return [
            Text::make('Name', 'name')
                ->rules('required')
                ->translatable(),
        ];
    }
}
```

When observing the request payload, I see this:

![Screenshot 2023-10-07 121351](https://github.com/Lupennat/nova-nested-many/assets/25797257/4f52141d-88be-45e9-8bf5-586c95a19db7)

Noting that it was working perfectly before making the `name` field translatable.

**Comment by wajdijurry** [comment]
It works like a charm after this fix. Thanks @Lupennat .

**Comment by milenishte** [comment]
I am using the latest module version and I have the problem when creating a new nested resource. The translatable field is saved with empty value. It works correctly when I edit it. I notice a difference in the request payload for the new and the existing entries. For example for the field title of my nested resource, here is a name for existing entry:
pageBlocks[4][title][de]
And like this for a new one:
pageBlocks[5][title.*][de]

I use https://github.com/outl1ne/nova-translatable . If I remove the ->translatable() method of the title field, it saves the title of the new resources.

**Comment by Lupennat** [comment]
nova-translatable do a "validationTrick" to append .* on attribute when the request is a POST or PUT.
I made an hack to bypass this problem when nova-nested-many serialize nested resource data.
