### ISSUE TITLE
Problem with 2 nested resources

### ISSUE THREAD

**Issue by BobbyBorisov** [Lupennat/nova-nested-many#15]
Hi, I have an issue when trying to create a resource that have 2 level nested resources, one in another. I guess it is intended to work, Basically my setup is 

Resource
* HasManyNested('Resource1')

Resource1
* HasManyNested('Resource2')

and I have all the necessary traits in the Nova resource class and Eloquent model classes as you mentioned in the doc.

the issue is that Resource1 is not saved, and somehow when I click create Resource 1 it gives me a bunch of Resource2 as well (at least 10 records)

**Comment by Lupennat** [comment]
I am sorry but multi-level nesting is not yet supported.

**Comment by BobbyBorisov** [comment]
@Lupennat sorry, I thought its supported because I saw your package is based on https://github.com/yassilah/laravel-nova-nested-form.

I found one workaround which is not ideal but I think it works and it is to have HasManyNested and inside to have Repeatable field from Nova 4, but of build-in support in your package would be better. 

Thank for hard work! 
Cheers

**Comment by leonardo-max** [comment]
Would it be possible to release an update allowing more than 2 resources?

**Comment by Lupennat** [comment]
Unfortunately, this is not a minor change. I do not guarantee it will be implemented anytime soon.

**Comment by Lupennat** [comment]
V2.10 and v1.6.4 now support recursivity of nested many, [here](https://github.com/Lupennat/nova-nested-many?tab=readme-ov-file#recursivity) you can find more infos.
