### ISSUE TITLE
Compatibility with mostafaznv/nova-ckeditor

### ISSUE THREAD

**Issue by milenishte** [Lupennat/nova-nested-many#16]
Hi,
I have a problem with a nested resource that has a CkEditor 5 field using the mostafaznv/nova-ckeditor module.
When submitting the form, the value of the field is not retrieved, so it is submitted as an empty value.
Not sure if it isn't a problem of the CkEditor module, but any advise is welcome.

Thanks!

**Comment by Lupennat** [comment]
nova-ckeditor package store the editor reference inside a vue $options object. The key used to store editor is not unique because does not use formUniqueId, but only the field attribute.

**Comment by Lupennat** [comment]
[PR opened](https://github.com/mostafaznv/nova-ckeditor/pull/91)

**Comment by Lupennat** [comment]
PR merged
