### ISSUE TITLE
DefaultChildren not updated

### ISSUE THREAD

**Issue by Keko-94** [Lupennat/nova-nested-many#5]
Hello,

The defaultchildren doesn't update in the vue:
Demo: https://clipchamp.com/watch/r8SfdouYsPf

`Select::make('Size')->options([
                'S' => 'Small',
                'M' => 'Medium',
                'L' => 'Large',
            ]),

            HasManyNested::make('Posts', Post::class)
                ->dependsOn('size', function (HasManyNested $field, NovaRequest $request, FormData $formData) {
                    if ($formData->size === 'S') {
                        $field->defaultChildren([['title' => 'Small']]);
                    } else {
                        $field->defaultChildren([['title' => 'Not small']]);
                    }
                })`

Thanks

**Comment by Lupennat** [comment]
DefaultChildren are generated exclusively when no children exist.
In this specific case dependsOn is triggered immediately and generates the default with title 'Not Small'.
By changing type from the select, the update is invoked but since a children already exists, updated defaultChildren is not used.
If you want to change content of children based on parent field, you should use `propagate` on parent resource

```php
public function fields(NovaRequest $request)
    {
              Select::make('type')
                ->options([
                    'S' => 'Small',
                    'M' => 'Medium',
                    'L' => 'Large'
                ]),

            HasManyNested::make('Posts', Post::class)
                    ->defaultChildren([[]])
                    ->propagate('type')
                    ->rules('required', 'array', 'min:1')
    }
```
and something like that on `Post` resource

```php
public function fields(NovaRequest $request)
    {

        return [
            Text::make('Title', 'title', function($value) use($request) {
                return match($request->getNestedPropagated('type')) {
                        'S' => 'Small Title',
                        default => 'Not Small Title'
                    };
            })
        ];
    }
```

maybe the example is not a real situation, but this solution might be useful if based on the type, you want to render a Text field rather than Textarea or change validation rules on child.

**Comment by Keko-94** [comment]
In fact, this what I try to achieve:

```
Select::make('Type')->options([
                'S' => 'Single',
                'G' => 'Group',
            ]),

HasManyNested::make('Posts', 'post', Post::class)
                ->dependsOn('type', function (HasManyNested $field, NovaRequest $request, FormData $formData) {
                    if ($formData->type === 'S') {
                        $field->defaultChildren([['title' => '']]);
                    } else if ($formData->type) {
                        $field->defaultChildren([['title' => ''], ['title' => '']]);
                    }

                })
```

I really would like to have at least 2 children if I select Group, and if I switch to Single, I want to have only one.
Any idea would be appreciate!

**Comment by Lupennat** [comment]
You should be able to achieve it, with new tag 1.5.0
```php
            Select::make('Type')->options([
                    'S' => 'Single',
                    'G' => 'Group',
                ])
                ->readonly(function(NovaRequest $request) {
                    return $request->isUpdateOrUpdateAttachedRequest();
                })
                ->default('S'),

            HasManyNested::make('Posts', 'post', Post::class)
                ->dependsOn('type', function(HasManyNested $field, NovaRequest $novaRequest, FormData $formData) {
                    if($formData->type === 'G') {
                        $field->defaultChildren([['title' => ''],['title' => '']], true)->min(2)->rules('required', 'array', 'min:2');
                    } else {
                        $field->defaultChildren([['title' => '']], true)->min(1)->max(1)->rules('required', 'array', 'min:1', 'max:1');
                    }
                })
```
