### ISSUE TITLE
HasNestedMany with nested fields in DependencyContainer

### ISSUE THREAD

**Issue by wajdijurry** [Lupennat/nova-nested-many#9]
I am using this package to nest a relation into other resource. In my case, I am nesting `Variation` resource into `Product` resource.

The `Variation` resource has the following fields:
```
// opt-out code
            Boolean::make('Enable Sale Price?', 'sale_price', function ($value) {
                return !is_null($value);
            }),

            DependencyContainer::make([
                Currency::make('Sale Price', 'sale_price')
                    ->currency('JOD'),
            ])->dependsOnNotEmpty('sale_price'),
// opt-out code
```

And the `Product` resource has this:
```
            HasManyNested::make('Variations', 'variations', Variation::class)
                ->propagate('id')
                ->hideFromIndex()
                ->useTabs(),
```

Something weird is going on, as illustrated in the attached video, when I check "Enable Sale Price?" for the second Variation, the first Variation got affected by this change.

This bug applies to all fields in `DependencyContainer` in the `Variation` resource.

[screencast-admin.otomech.local-2023.10.04-19_01_26.webm](https://github.com/Lupennat/nova-nested-many/assets/25797257/e057a75b-5164-4b79-95cb-93c16456ef0e)

**Comment by wajdijurry** [comment]
I figured out that the fields in the first Variation have the same IDs as the second Variation. I believe this is the case but I lack the experience to edit the fields templates in Vue.js

**Comment by Lupennat** [comment]
can you please provide me a link of dependency container package?

**Comment by Lupennat** [comment]
discussion moved [here](https://github.com/alexwenzel/nova-dependency-container/issues/39)
